[2021-04-25 00:07:55,822] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: bash_operator_dag.second_task 2021-02-10T00:00:00+00:00 [queued]>
[2021-04-25 00:07:55,876] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: bash_operator_dag.second_task 2021-02-10T00:00:00+00:00 [queued]>
[2021-04-25 00:07:55,877] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 00:07:55,877] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2021-04-25 00:07:55,878] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 00:07:55,947] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): second_task> on 2021-02-10T00:00:00+00:00
[2021-04-25 00:07:55,955] {standard_task_runner.py:52} INFO - Started process 1548 to run task
[2021-04-25 00:07:55,981] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'bash_operator_dag', 'second_task', '2021-02-10T00:00:00+00:00', '--job-id', '551', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/simple_bash_operator_dag.py', '--cfg-path', '/tmp/tmpqowbeu_n', '--error-file', '/tmp/tmpyd24icu1']
[2021-04-25 00:07:55,982] {standard_task_runner.py:77} INFO - Job 551: Subtask second_task
[2021-04-25 00:07:56,128] {logging_mixin.py:104} INFO - Running <TaskInstance: bash_operator_dag.second_task 2021-02-10T00:00:00+00:00 [running]> on host 4a00a306afdc
[2021-04-25 00:07:56,297] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bash_operator_dag
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-02-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-10T00:00:00+00:00
[2021-04-25 00:07:56,298] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-25 00:07:56,300] {bash.py:158} INFO - Running command: echo "testing second bash operator"
[2021-04-25 00:07:56,339] {bash.py:169} INFO - Output:
[2021-04-25 00:07:56,349] {bash.py:173} INFO - testing second bash operator
[2021-04-25 00:07:56,350] {bash.py:177} INFO - Command exited with return code 0
[2021-04-25 00:07:56,540] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=bash_operator_dag, task_id=second_task, execution_date=20210210T000000, start_date=20210425T000755, end_date=20210425T000756
[2021-04-25 00:07:56,737] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-25 00:07:56,781] {local_task_job.py:146} INFO - Task exited with return code 0
[2021-04-25 00:44:25,519] {taskinstance.py:871} INFO - Dependencies not met for <TaskInstance: bash_operator_dag.second_task 2021-02-10T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'first_task'}
[2021-04-25 00:44:25,527] {local_task_job.py:93} INFO - Task is not able to be run
